@CovidApi_HostAddress = http://localhost:5085

GET {{CovidApi_HostAddress}}/weatherforecast/
Accept: application/json

### GET all CovidCases
GET {{CovidApi_HostAddress}}/api/CovidCases
Accept: application/json

### GET CovidCase by ID
GET {{CovidApi_HostAddress}}/api/CovidCases/1
Accept: application/json

### GET Get Latest CovidCases By Country
GET {{CovidApi_HostAddress}}/api/CovidCases/latest?country=Canada
Accept: application/json

